In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('actor.csv', encoding='latin1')
df1 = pd.read_csv('category.csv', encoding='latin1')
df2 = pd.read_csv('film.csv', encoding='latin1')
df3 = pd.read_csv('inventory.csv', encoding='latin1')
df4 = pd.read_csv('language.csv', encoding='latin1')
df5 = pd.read_csv('old_HDD.csv', encoding='latin1')
df6 = pd.read_csv('rental.csv', encoding='latin1')

In [3]:
actor = df.copy()
category = df1.copy()
film = df2.copy()
inventory = df3.copy()
language = df4.copy()
old = df5.copy()
rental = df6.copy()

In [4]:
actor.head()

actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2006-02-15 04:34:33
1         2       NICK      WAHLBERG  2006-02-15 04:34:33
2         3         ED         CHASE  2006-02-15 04:34:33
3         4   JENNIFER         DAVIS  2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA  2006-02-15 04:34:33

In [5]:
nancols = actor.isnull().sum()
nancols[nancols>0]               # NO HAY NINGÚN VALOR NULO EN ACTOR

Series([], dtype: int64)

In [6]:
actor.nunique()


actor_id       200
first_name     128
last_name      121
last_update      1
dtype: int64

In [7]:
actor['name'] = actor.first_name.str.cat(actor.last_name, sep= ' ') # NUEVA COLUMNA CON EL NOMBRE COMPLETO

In [8]:
actor.head()   # AHORA BORRO LAS COLUMNAS DE FIRS NAME Y LAST NAME

actor_id first_name     last_name          last_update                 name
0         1   PENELOPE       GUINESS  2006-02-15 04:34:33     PENELOPE GUINESS
1         2       NICK      WAHLBERG  2006-02-15 04:34:33        NICK WAHLBERG
2         3         ED         CHASE  2006-02-15 04:34:33             ED CHASE
3         4   JENNIFER         DAVIS  2006-02-15 04:34:33       JENNIFER DAVIS
4         5     JOHNNY  LOLLOBRIGIDA  2006-02-15 04:34:33  JOHNNY LOLLOBRIGIDA

In [9]:
actor.drop(['first_name', 'last_name', 'last_update'], axis =1, inplace = True)

In [10]:
actor.head()

actor_id                 name
0         1     PENELOPE GUINESS
1         2        NICK WAHLBERG
2         3             ED CHASE
3         4       JENNIFER DAVIS
4         5  JOHNNY LOLLOBRIGIDA

In [11]:
actor.nunique()

actor_id    200
name        199
dtype: int64

In [12]:
actor['name'].value_counts().head()   # SE REPITE SUSAN DAVIS BORRO EL DE ID 110

SUSAN DAVIS       2
EWAN GOODING      1
DARYL CRAWFORD    1
GRETA KEITEL      1
JANE JACKMAN      1
Name: name, dtype: int64

In [13]:
actor[actor.name == 'SUSAN DAVIS']

actor_id         name
100       101  SUSAN DAVIS
109       110  SUSAN DAVIS

In [14]:
# BORRO LA LINEA 109 CON ID 110 

In [15]:
actor.drop([109], axis= 0, inplace = True)

In [16]:
actor.reset_index(drop=True).tail()

actor_id           name
194       196    BELA WALKEN
195       197     REESE WEST
196       198    MARY KEITEL
197       199  JULIA FAWCETT
198       200   THORA TEMPLE

In [17]:
# CATEGORY DATAFRAME

In [18]:
category.head()

category_id       name          last_update
0            1     Action  2006-02-15 04:46:27
1            2  Animation  2006-02-15 04:46:27
2            3   Children  2006-02-15 04:46:27
3            4   Classics  2006-02-15 04:46:27
4            5     Comedy  2006-02-15 04:46:27

In [19]:
category.shape

(16, 3)

In [20]:
nancols = category.isnull().sum()
nancols[nancols>0]            # NO HAY NINGÚN VALOR NULO EN CATEGORY

Series([], dtype: int64)

In [21]:
category.nunique()

category_id    16
name           16
last_update     1
dtype: int64

In [22]:
category.name.unique()

array(['Action', 'Animation', 'Children', 'Classics', 'Comedy',
       'Documentary', 'Drama', 'Family', 'Foreign', 'Games', 'Horror',
       'Music', 'New', 'Sci-Fi', 'Sports', 'Travel'], dtype=object)

In [23]:
category.name.replace('Sci-Fi', 'Science fiction', inplace = True)

In [24]:
category.name.unique()

array(['Action', 'Animation', 'Children', 'Classics', 'Comedy',
       'Documentary', 'Drama', 'Family', 'Foreign', 'Games', 'Horror',
       'Music', 'New', 'Science fiction', 'Sports', 'Travel'],
      dtype=object)

In [25]:
category.category_id.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int64)

In [26]:
category.drop(['last_update'], axis= 1, inplace = True)  # BORRO LAST_UPDATE

In [27]:
category.reset_index(drop=True).head()

category_id       name
0            1     Action
1            2  Animation
2            3   Children
3            4   Classics
4            5     Comedy

In [28]:
category.shape

(16, 2)

In [29]:
#  FILM DATAFRAME

In [30]:
film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  release_year  \
0  A Epic Drama of a Feminist And a Mad Scientist...          2006   
1  A Astounding Epistle of a Database Administrat...          2006   
2  A Astounding Reflection of a Lumberjack And a ...          2006   
3  A Fanciful Documentary of a Frisbee And a Lumb...          2006   
4  A Fast-Paced Documentary of a Pastry Chef And ...          2006   

   language_id  original_language_id  rental_duration  rental_rate  length  \
0            1                   NaN                6         0.99      86   
1            1                   NaN                3         4.99      48   
2            1                   NaN                7         2.99      50   
3            1                   NaN                5         2.99     117   
4            1                   NaN                6         2.99     130   

   replacement_cost rating                  special_features  \
0             20.99     PG  Deleted Scenes,Behind the Scenes   
1             12.99      G           Trailers,Deleted Scenes   
2             18.99  NC-17           Trailers,Deleted Scenes   
3             26.99      G    Commentaries,Behind the Scenes   
4             22.99      G                    Deleted Scenes   

           last_update  
0  2006-02-15 05:03:42  
1  2006-02-15 05:03:42  
2  2006-02-15 05:03:42  
3  2006-02-15 05:03:42  
4  2006-02-15 05:03:42

In [31]:
film.shape

(1000, 13)

In [32]:
film.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   film_id               1000 non-null   int64  
 1   title                 1000 non-null   object 
 2   description           1000 non-null   object 
 3   release_year          1000 non-null   int64  
 4   language_id           1000 non-null   int64  
 5   original_language_id  0 non-null      float64
 6   rental_duration       1000 non-null   int64  
 7   rental_rate           1000 non-null   float64
 8   length                1000 non-null   int64  
 9   replacement_cost      1000 non-null   float64
 10  rating                1000 non-null   object 
 11  special_features      1000 non-null   object 
 12  last_update           1000 non-null   object 
dtypes: float64(3), int64(5), object(5)
memory usage: 101.7+ KB


In [33]:
nancols = category.isnull().sum()
nancols[nancols>0]       # NO HAY NULOS EN FILM  

Series([], dtype: int64)

In [34]:
film.nunique()

film_id                 1000
title                   1000
description             1000
release_year               1
language_id                1
original_language_id       0
rental_duration            5
rental_rate                3
length                   140
replacement_cost          21
rating                     5
special_features          15
last_update                1
dtype: int64

In [35]:
film.original_language_id.unique()

array([nan])

In [36]:
film[film.title== 'ACADEMY DINOSAUR']    # LA TABLA OLD Y LA TABLA FILM TIENEN EL MISMO TITLE

film_id             title  \
0        1  ACADEMY DINOSAUR   

                                         description  release_year  \
0  A Epic Drama of a Feminist And a Mad Scientist...          2006   

   language_id  original_language_id  rental_duration  rental_rate  length  \
0            1                   NaN                6         0.99      86   

   replacement_cost rating                  special_features  \
0             20.99     PG  Deleted Scenes,Behind the Scenes   

           last_update  
0  2006-02-15 05:03:42

In [37]:
# BORRO last update y original lenguage id porque solo tiene nulos

In [38]:
film.drop(['last_update', 'original_language_id'], axis=1, inplace = True)

In [39]:
film.description.head()   # MAYUSCULAS EN CADA PALABRA

0    A Epic Drama of a Feminist And a Mad Scientist...
1    A Astounding Epistle of a Database Administrat...
2    A Astounding Reflection of a Lumberjack And a ...
3    A Fanciful Documentary of a Frisbee And a Lumb...
4    A Fast-Paced Documentary of a Pastry Chef And ...
Name: description, dtype: object

In [40]:
lista=[e.upper() for e in film.description]
film['description']= lista

In [41]:
film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  release_year  \
0  A EPIC DRAMA OF A FEMINIST AND A MAD SCIENTIST...          2006   
1  A ASTOUNDING EPISTLE OF A DATABASE ADMINISTRAT...          2006   
2  A ASTOUNDING REFLECTION OF A LUMBERJACK AND A ...          2006   
3  A FANCIFUL DOCUMENTARY OF A FRISBEE AND A LUMB...          2006   
4  A FAST-PACED DOCUMENTARY OF A PASTRY CHEF AND ...          2006   

   language_id  rental_duration  rental_rate  length  replacement_cost rating  \
0            1                6         0.99      86             20.99     PG   
1            1                3         4.99      48             12.99      G   
2            1                7         2.99      50             18.99  NC-17   
3            1                5         2.99     117             26.99      G   
4            1                6         2.99     130             22.99      G   

                   special_features  
0  Deleted Scenes,Behind the Scenes  
1           Trailers,Deleted Scenes  
2           Trailers,Deleted Scenes  
3    Commentaries,Behind the Scenes  
4                    Deleted Scenes

In [42]:
film.rental_duration.unique()

array([6, 3, 7, 5, 4], dtype=int64)

In [43]:
film.rental_rate.unique()

array([0.99, 4.99, 2.99])

In [44]:
# CAMBIO NOMBRES PARA EXPLICARLO MEJOR
film.rename(columns={'rental_rate': 'rental_price'}, inplace=True)
film.rename(columns={'length': 'length_min'}, inplace=True)
film.rename(columns={'rental_duration': 'rental_days'}, inplace=True)

In [45]:
film.length_min.unique()

array([ 86,  48,  50, 117, 130, 169,  62,  54, 114,  63, 126, 136, 150,
        94,  46, 180,  82,  57, 113,  79, 129,  85,  92, 181,  74, 179,
        91, 168, 119, 153, 147, 127, 121,  68,  99, 148, 137, 170,  83,
       108, 118, 162, 182,  75, 173,  87,  65,  90, 122, 160,  89, 175,
       106,  73, 151, 100,  53,  77, 142,  93, 163, 103,  61,  71, 102,
        76,  98,  72, 176, 123,  56, 161,  60, 133, 125,  67,  52, 120,
       167,  70, 135, 112, 183, 110, 152,  51, 146,  66, 185, 124, 107,
       101, 132, 143, 165,  81, 164,  58,  95, 139,  55, 149, 109,  59,
       172, 115, 184, 166,  64, 104,  69,  84, 144,  88, 141,  47,  49,
       177, 154, 159, 178,  96, 116, 171, 140, 155, 158, 174, 138,  97,
       131, 156,  80, 145, 111, 128, 157,  78, 105, 134], dtype=int64)

In [46]:
film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  release_year  \
0  A EPIC DRAMA OF A FEMINIST AND A MAD SCIENTIST...          2006   
1  A ASTOUNDING EPISTLE OF A DATABASE ADMINISTRAT...          2006   
2  A ASTOUNDING REFLECTION OF A LUMBERJACK AND A ...          2006   
3  A FANCIFUL DOCUMENTARY OF A FRISBEE AND A LUMB...          2006   
4  A FAST-PACED DOCUMENTARY OF A PASTRY CHEF AND ...          2006   

   language_id  rental_days  rental_price  length_min  replacement_cost  \
0            1            6          0.99          86             20.99   
1            1            3          4.99          48             12.99   
2            1            7          2.99          50             18.99   
3            1            5          2.99         117             26.99   
4            1            6          2.99         130             22.99   

  rating                  special_features  
0     PG  Deleted Scenes,Behind the Scenes  
1      G           Trailers,Deleted Scenes  
2  NC-17           Trailers,Deleted Scenes  
3      G    Commentaries,Behind the Scenes  
4      G                    Deleted Scenes

In [47]:
film.replacement_cost.unique()

array([20.99, 12.99, 18.99, 26.99, 22.99, 17.99, 28.99, 15.99, 21.99,
       24.99, 16.99, 23.99, 10.99, 14.99, 27.99,  9.99, 19.99, 11.99,
       29.99, 25.99, 13.99])

In [48]:
film.rating.unique()   # LO CAMBIO POR EL NOMBRE COMPLETO

array(['PG', 'G', 'NC-17', 'PG-13', 'R'], dtype=object)

In [49]:
film.rating.replace({'PG': 'Parental Guidance Suggested', 'G': 'General Audiences', 'NC-17': 'Adults Only', 'PG-13': 'Parents Strongly Cautioned', 'R': 'Restricted'}, inplace= True)

In [50]:
film.special_features.unique()

array(['Deleted Scenes,Behind the Scenes', 'Trailers,Deleted Scenes',
       'Commentaries,Behind the Scenes', 'Deleted Scenes', 'Trailers',
       'Commentaries,Deleted Scenes',
       'Trailers,Deleted Scenes,Behind the Scenes',
       'Trailers,Commentaries,Behind the Scenes', 'Trailers,Commentaries',
       'Trailers,Behind the Scenes',
       'Commentaries,Deleted Scenes,Behind the Scenes',
       'Trailers,Commentaries,Deleted Scenes',
       'Trailers,Commentaries,Deleted Scenes,Behind the Scenes',
       'Behind the Scenes', 'Commentaries'], dtype=object)

In [51]:
lista=[e.upper() for e in film.special_features]
film['special_features']= lista

In [52]:
film.special_features.unique()

array(['DELETED SCENES,BEHIND THE SCENES', 'TRAILERS,DELETED SCENES',
       'COMMENTARIES,BEHIND THE SCENES', 'DELETED SCENES', 'TRAILERS',
       'COMMENTARIES,DELETED SCENES',
       'TRAILERS,DELETED SCENES,BEHIND THE SCENES',
       'TRAILERS,COMMENTARIES,BEHIND THE SCENES', 'TRAILERS,COMMENTARIES',
       'TRAILERS,BEHIND THE SCENES',
       'COMMENTARIES,DELETED SCENES,BEHIND THE SCENES',
       'TRAILERS,COMMENTARIES,DELETED SCENES',
       'TRAILERS,COMMENTARIES,DELETED SCENES,BEHIND THE SCENES',
       'BEHIND THE SCENES', 'COMMENTARIES'], dtype=object)

In [53]:
film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  release_year  \
0  A EPIC DRAMA OF A FEMINIST AND A MAD SCIENTIST...          2006   
1  A ASTOUNDING EPISTLE OF A DATABASE ADMINISTRAT...          2006   
2  A ASTOUNDING REFLECTION OF A LUMBERJACK AND A ...          2006   
3  A FANCIFUL DOCUMENTARY OF A FRISBEE AND A LUMB...          2006   
4  A FAST-PACED DOCUMENTARY OF A PASTRY CHEF AND ...          2006   

   language_id  rental_days  rental_price  length_min  replacement_cost  \
0            1            6          0.99          86             20.99   
1            1            3          4.99          48             12.99   
2            1            7          2.99          50             18.99   
3            1            5          2.99         117             26.99   
4            1            6          2.99         130             22.99   

                        rating                  special_features  
0  Parental Guidance Suggested  DELETED SCENES,BEHIND THE SCENES  
1            General Audiences           TRAILERS,DELETED SCENES  
2                  Adults Only           TRAILERS,DELETED SCENES  
3            General Audiences    COMMENTARIES,BEHIND THE SCENES  
4            General Audiences                    DELETED SCENES

In [54]:
# INVENTORY DATAFRAME

In [55]:
inventory.head()

inventory_id  film_id  store_id          last_update
0             1        1         1  2006-02-15 05:09:17
1             2        1         1  2006-02-15 05:09:17
2             3        1         1  2006-02-15 05:09:17
3             4        1         1  2006-02-15 05:09:17
4             5        1         2  2006-02-15 05:09:17

In [56]:
inventory.shape

(1000, 4)

In [57]:
inventory.nunique()

inventory_id    1000
film_id          207
store_id           2
last_update        1
dtype: int64

In [58]:
inventory.drop(['last_update'], axis=1, inplace= True)  #BORRO LAST UPDATE

In [59]:
inventory.film_id.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  34,  35,  37,  39,  40,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 145, 146, 147, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 172, 173, 174, 175, 176, 177, 178, 179, 180,
       181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 19

In [60]:
inventory.inventory_id.unique()

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [61]:
inventory.head()

inventory_id  film_id  store_id
0             1        1         1
1             2        1         1
2             3        1         1
3             4        1         1
4             5        1         2

In [62]:
# LANGUAGE DATAFRAME

In [63]:
language

language_id      name          last_update
0            1   English  2006-02-15 05:02:19
1            2   Italian  2006-02-15 05:02:19
2            3  Japanese  2006-02-15 05:02:19
3            4  Mandarin  2006-02-15 05:02:19
4            5    French  2006-02-15 05:02:19
5            6    German  2006-02-15 05:02:19

In [64]:
language.drop(['last_update'], axis=1, inplace= True)  #BORRO LAST UPDATE

In [65]:
language.nunique()

language_id    6
name           6
dtype: int64

In [66]:
language.name.unique()

array(['English', 'Italian', 'Japanese', 'Mandarin', 'French', 'German'],
      dtype=object)

In [67]:
language

language_id      name
0            1   English
1            2   Italian
2            3  Japanese
3            4  Mandarin
4            5    French
5            6    German

In [68]:
# OLD DATAFRAME

In [69]:
old.head()

first_name last_name                  title  release_year  category_id
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14

In [70]:
old.shape

(1000, 5)

In [71]:
old['name'] = old.first_name.str.cat(old.last_name, sep= ' ') # NUEVA COLUMNA CON EL NOMBRE

In [72]:
old.drop(['first_name', 'last_name'], axis= 1, inplace = True)

In [73]:
old.head()

title  release_year  category_id              name
0       ACADEMY DINOSAUR          2006            6  PENELOPE GUINESS
1   ANACONDA CONFESSIONS          2006            2  PENELOPE GUINESS
2            ANGELS LIFE          2006           13  PENELOPE GUINESS
3  BULWORTH COMMANDMENTS          2006           10  PENELOPE GUINESS
4          CHEAPER CLYDE          2006           14  PENELOPE GUINESS

In [74]:
old.nunique()

title           614
release_year      1
category_id      16
name             39
dtype: int64

In [75]:
old.name.unique()

array(['PENELOPE GUINESS', 'NICK WAHLBERG', 'ED CHASE', 'JENNIFER DAVIS',
       'JOHNNY LOLLOBRIGIDA', 'BETTE NICHOLSON', 'GRACE MOSTEL',
       'MATTHEW JOHANSSON', 'JOE SWANK', 'CHRISTIAN GABLE', 'ZERO CAGE',
       'KARL BERRY', 'UMA WOOD', 'VIVIEN BERGEN', 'CUBA OLIVIER',
       'FRED COSTNER', 'HELEN VOIGHT', 'DAN TORN', 'BOB FAWCETT',
       'LUCILLE TRACY', 'KIRSTEN PALTROW', 'ELVIS MARX', 'SANDRA KILMER',
       'CAMERON STREEP', 'KEVIN BLOOM', 'RIP CRAWFORD', 'JULIA MCQUEEN',
       'WOODY HOFFMAN', 'ALEC WAYNE', 'SANDRA PECK', 'SISSY SOBIESKI',
       'TIM HACKMAN', 'MILLA PECK', 'AUDREY OLIVIER', 'JUDY DEAN',
       'BURT DUKAKIS', 'VAL BOLGER', 'TOM MCKELLEN', 'GOLDIE BRODY'],
      dtype=object)

In [76]:
old.category_id.unique()

array([ 6,  2, 13, 10, 14,  4, 11, 15,  8,  3,  9,  5, 12,  1, 16,  7],
      dtype=int64)

In [77]:
# RENTAL DATAFRAME

In [78]:
rental.head()

rental_id          rental_date  inventory_id  customer_id  \
0          1  2005-05-24 22:53:30           367          130   
1          2  2005-05-24 22:54:33          1525          459   
2          3  2005-05-24 23:03:39          1711          408   
3          4  2005-05-24 23:04:41          2452          333   
4          5  2005-05-24 23:05:21          2079          222   

           return_date  staff_id          last_update  
0  2005-05-26 22:04:30         1  2006-02-15 21:30:53  
1  2005-05-28 19:40:33         1  2006-02-15 21:30:53  
2  2005-06-01 22:12:39         1  2006-02-15 21:30:53  
3  2005-06-03 01:43:41         2  2006-02-15 21:30:53  
4  2005-06-02 04:33:21         1  2006-02-15 21:30:53

In [79]:
rental.drop(['last_update'], axis=1, inplace= True)  #BORRO LAST UPDATE

In [80]:
rental.shape

(1000, 6)

In [81]:
import datetime as dt
import regex as re

In [82]:
lista=[]

for e in rental.rental_date:
    e=str(e)
    lista.append((re.findall('[0-9]+-[0-9]+-[0-9]+', e)[0]))
    
rental['rental_date']=lista

In [83]:
lista=[]

for e in rental.return_date:
    e=str(e)
    lista.append((re.findall('[0-9]+-[0-9]+-[0-9]+', e)[0]))
    
rental['return_date']=lista

In [84]:
rental.head()

rental_id rental_date  inventory_id  customer_id return_date  staff_id
0          1  2005-05-24           367          130  2005-05-26         1
1          2  2005-05-24          1525          459  2005-05-28         1
2          3  2005-05-24          1711          408  2005-06-01         1
3          4  2005-05-24          2452          333  2005-06-03         2
4          5  2005-05-24          2079          222  2005-06-02         1

In [85]:
rental['rental_date'] = rental['rental_date'].astype('datetime64[ns]')
rental['return_date'] = rental['return_date'].astype('datetime64[ns]')

In [86]:
rental.dtypes

rental_id                int64
rental_date     datetime64[ns]
inventory_id             int64
customer_id              int64
return_date     datetime64[ns]
staff_id                 int64
dtype: object

In [87]:
rental.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   rental_id     1000 non-null   int64         
 1   rental_date   1000 non-null   datetime64[ns]
 2   inventory_id  1000 non-null   int64         
 3   customer_id   1000 non-null   int64         
 4   return_date   1000 non-null   datetime64[ns]
 5   staff_id      1000 non-null   int64         
dtypes: datetime64[ns](2), int64(4)
memory usage: 47.0 KB


In [88]:
# rental['rental_time'] = rental['return_date'].sub(rental['rental_date'], axis =0)

In [89]:
rental['rent_days'] =  (rental['return_date'] - rental['rental_date']).dt.days 

In [90]:
rental.head()

rental_id rental_date  inventory_id  customer_id return_date  staff_id  \
0          1  2005-05-24           367          130  2005-05-26         1   
1          2  2005-05-24          1525          459  2005-05-28         1   
2          3  2005-05-24          1711          408  2005-06-01         1   
3          4  2005-05-24          2452          333  2005-06-03         2   
4          5  2005-05-24          2079          222  2005-06-02         1   

   rent_days  
0          2  
1          4  
2          8  
3         10  
4          9

In [91]:
rental.inventory_id.unique()

array([ 367, 1525, 1711, 2452, 2079, 2792, 3995, 2346, 2580, 1824, 4443,
       1584, 2294, 2701, 3049,  389,  830, 3376, 1941, 3517,  146,  727,
       4441, 3273, 3961, 4371, 1225, 4068,  611, 3744, 4482, 3832, 1681,
       2613, 1286, 1308,  403, 2540, 4466, 2638, 1761,  380, 2578, 3098,
       1853, 3318, 2211, 1780, 2965, 1983, 1257, 4017, 1255, 2787, 1139,
       1352, 3938, 3050, 2884,  330, 4210,  261, 4008,   79, 3552, 1162,
        239, 4029, 3207, 2168, 2408, 2260,  517, 1744, 3393, 3021, 1303,
       4067, 3299, 2478, 2610, 1388,  466, 1829,  470, 2275, 1586, 2221,
       2181, 2984,  139,  775, 4360, 1675,  178, 3418, 1283, 2970,  535,
       2599,  617,  373, 3343, 4281,  794, 3627, 2833, 3289, 1044, 4108,
       3725, 2153, 2963, 4502,  749, 4453, 4278,  872, 1359,   37, 1053,
       2908, 1795,  212,  952, 2047, 2026, 4322, 4154, 3990,  815, 3367,
        399, 2272,  103, 2296, 2591, 4134,  327,  655,  811, 4407,  847,
       1689, 3905, 1431,  633, 4252, 1084,  909, 29

In [92]:
# %pip install mysql-connector-python

In [93]:
# %pip install pymysql

In [94]:
import mysql.connector as conn
from sqlalchemy import create_engine


In [95]:
str_conn='mysql+pymysql://root:password@127.0.0.1:3306'

cursor=create_engine(str_conn)


In [96]:
cursor.execute('drop database if exists alquiler;')
cursor.execute('create database alquiler;')

In [97]:
str_conn='mysql+pymysql://root:password@127.0.0.1:3306/alquiler'

In [98]:
cursor_db = create_engine(str_conn)

In [99]:
actor.to_sql(name='actor', con=cursor_db, if_exists='replace', index=False)

199

In [100]:
category.to_sql(name='category', con=cursor_db, if_exists='replace', index=False)

16

In [101]:
film.to_sql(name='film', con=cursor_db, if_exists='replace', index=False)

1000

In [102]:
inventory.to_sql(name='inventory', con=cursor_db, if_exists='replace', index=False)

1000

In [103]:
language.to_sql(name='language', con=cursor_db, if_exists='replace', index=False)

6

In [104]:
rental.to_sql(name='rental', con=cursor_db, if_exists='replace', index=False)

1000